apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.webFrontendService.name }}-registry-secret"
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ werf_secret_file ".dockerconfigjson" | b64enc }}
