apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.webFrontendService.name }}"
  namespace: {{ .Values.global.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.webFrontendService.port }}
  selector:
    service: "{{ .Values.webFrontendService.name }}"

